package br.com.fiap.cheffy.shared.exception.keys;

public enum ExceptionsKeys {
    //General Error Messages
    GENERIC_RESOURCE_NOT_FOUND,
    PROPERTY_BINDING_ERROR,
    INVALID_FORMAT_ERROR,
    ERROR_ON_DESERIALIZATION,
    GENERIC_ERROR_MESSAGE,
    ARGUMENT_NOT_VALID_ERROR,
    INVALID_OPERATION_EXCEPTION,

    //Profile
    PROFILE_NOT_FOUND_EXCEPTION,
    PROFILE_ALREADY_EXIST_EXCEPTION,
    PROFILE_DATA_NOT_VALID,
    PROFILE_IS_OWNER_OR_CLIENT,


    //Adress
    ADDRESS_NOT_FOUND_EXCEPTION,
    FIRST_ADDRESS_MUST_BE_MAIN,

    //User
    USER_NOT_FOUND_EXCEPTION,
    REGISTER_FAILED_EXCEPTION,
    USER_MUST_HAVE_AT_LEAST_ONE_ADDRESS,
    USER_HAS_ACTIVE_RESTAURANT,
    USER_IS_ALREADY_INACTIVE,
    USER_IS_ALREADY_ACTIVE,

    //Login
    LOGIN_FAILED_EXCEPTION,

    //Auth
    TOKEN_EXPIRED_EXCEPTION,
    INVALID_PASSWORD_MSG,
    INVALID_POSTAL_CODE_MSG,

    //RESTAURANT
    RESTAURANT_INVALID_WORKING_TIME,
    WORKING_TIME_TOO_SHORT,
    RESTAURANT_ALREADY_EXIST,
    AROUND_THE_CLOCK_RESTAURANTS_SHOULDNT_DECLARE_WORKING_HOURS,
    ZONE_ID_DO_NOT_EXIST,
    RESTAURANT_NOT_FOUND_EXCEPTION,
    RESTAURANT_USER_DOES_NOT_HAVE_OWNERSHIP_OR_IS_INACTIVE,
    RESTAURANT_IS_ALREADY_INACTIVE,
    RESTAURANT_IS_ALREADY_ACTIVE,
    RESTAURANT_IS_INACTIVE_CANNOT_UPDATE,
    RESTAURANT_DOES_NOT_EXIST,
    RESTAURANT_IS_INACTIVE,

    //FoodItem
    FOOD_ITEM_ALREADY_EXIST,
    FOOD_ITEM_NOT_FOUND,
    FOOD_ITEM_IS_ALREADY_INACTIVE,
    FOOD_ITEM_IS_ALREADY_ACTIVE,
    FOOD_ITEM_INACTIVE_CANNOT_UPDATE_AVAILABILITY,
    FOOD_ITEM_UNAVAILABLE_CANNOT_ENABLE_DELIVERY,
    FOOD_ITEM_DOES_NOT_EXIST,
    FOOD_ITEM_DOES_NOT_EXIST_IN_RESTAURANT,
    FOOD_ITEM_NOT_FOUND_EXCEPTION
}