services:
  postgres:
    image: postgres:18.0
    environment:
    - POSTGRES_DB=cheffy
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      # Mount the init script directory
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - cheffy-network

    env_file:
      - .env

  cheffy-app:
    # Constrói a imagem a partir do Dockerfile no diretório atual
    build:
      context: .
      args:
        # Passa o valor para o Dockerfile. O nome do host é 'postgres' (o nome do serviço)
        DB_HOST_ARG: $DB_HOST
        POSTGRES_PASSWORD_ARG: $POSTGRES_PASSWORD
        DB_PORT_ARG: $DB_PORT
    ports:
      - "8080:8080"
    networks:
      - cheffy-network
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_PORT: "${DB_PORT}"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRAFT CONFIG
      # It's needed if we want to use kafka without depend on Zookeeper
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker, controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      # NETWORK LISTENERS
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      #Cluster Setup
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - cheffy-network

  auth-service:
    image: rodfc773/auth-service
    container_name: auth-service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_ISSUER=${JWT_ISSUER}
      - PRIVATE_KEY_PATH=${PRIVATE_KEY_PATH}
      - PUBLIC_KEY_PATH=${PUBLIC_KEY_PATH}
      - KEY_DIR=${KEY_DIR}
      - DB_NAME=${DB_NAME}
    ports:
      - "8085:8085"
    networks:
      - cheffy-network

  mongoDb:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - cheffy-network

networks:
  cheffy-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
